### ISSUE TITLE
SO_REUSEPORT undefined

### ISSUE THREAD

**Issue by genio** [genio/p5-UV#3]
We need to likely remove ```ReusePort=>1,``` on socket server and client creation:

https://github.com/genio/p5-UV/blob/master/t/05-poll.t#L401
https://github.com/genio/p5-UV/blob/master/t/05-poll.t#L423

I can't currently recall why this was necessary or if it was just the result of the straight 1-1 port of the libuv test.

```
#   Failed test 'No tests run for subtest "poll_duplex"'
#   at t/05-poll.t line 466.
Your vendor has not defined Socket macro SO_REUSEPORT, used at /opt/perl-5.24.0/lib/5.24.0/x86_64-linux/IO/Socket/INET.pm line 194
```

**Comment by genio** [comment]
The full CPAN Testers report is here: http://www.cpantesters.org/cpan/report/59886c08-7f91-11e7-a162-ba033d06fa27

**Comment by Leont** [comment]
`SO_REUSEPORT` was introduced in Linux 3.9, but that smoker is running 3.2. It probably needs to be conditional.

**Comment by genio** [comment]
Fixed in https://github.com/genio/p5-UV/commit/dc4d4bdb761c9be521922fa9e3c4dfc28ddee22f
