### ISSUE TITLE
Subtests not running

### ISSUE THREAD

**Issue by genio** [genio/p5-UV#4]
On FreeBSD, the IO::KQueue subtest seems to be failing:

```
t/05-poll-closesocket.t ................. 
No subtests run 
Argument "IO::KQueue::EVFILT_READ" isn't numeric in subroutine entry at t/05-poll.t line 538.
Argument "IO::KQueue::EV_ADD" isn't numeric in subroutine entry at t/05-poll.t line 538.
t/05-poll.t ............................. ok

Test Summary Report
-------------------
t/05-poll-closesocket.t               (Wstat: 9 Tests: 0 Failed: 0)
  Non-zero wait status: 9
  Parse errors: No plan found in TAP output
Files=16, Tests=829, 212 wallclock secs ( 0.14 usr  0.34 sys +  0.29 cusr  1.59 csys =  2.37 CPU)
Result: FAIL
Failed 1/16 test programs. 0/829 subtests failed.
*** Error code 255

Stop.
make: stopped in /home/cpansand/.cpan/build/2017081306/UV-1.000000_01-8
```

http://www.cpantesters.org/cpan/report/1d137d50-8039-11e7-b9d0-9be8f9b5093d

**Comment by Leont** [comment]
At first sight it looks to me like these warnings are not related to the crash (they appear to be in a different test)

**Comment by genio** [comment]
Looks like you're correct. Maybe stripping out the senseless subtest would improve things.

**Comment by genio** [comment]
It also appears that I'm an idiot an this test was intended to only run on Windows

**Comment by genio** [comment]
The cause of the error was that it was not finishing within a reasonable time period, so Test::Simple quit waiting and this warning came about. To fix this, we made ```t/05-poll-closesocket.t``` a Windows-only test as it was intended to be.
