### ISSUE TITLE
Socket Required version bump

### ISSUE THREAD

**Issue by genio** [genio/p5-UV#8]
http://www.cpantesters.org/cpan/report/2a195384-8841-11e7-a074-e1beba07c9dd

5.8.9 ships with Socket v1.81

1.81 did not have ```IPPROTO_IP``` defined. There isn't a change log before 1.95, but 1.95 does indeed have ```IPPROTO_IP```.  Bumping the prereq to be at least version 1.95 seems to be a sane solution.

**Comment by Leont** [comment]
That's making no sense. `IPPROTO_IP` was added in in [1.80](https://perl5.git.perl.org/perl.git/commitdiff/131c565afbb207eedaa0a3a4458b1e0ef2716db7)

**Comment by genio** [comment]
hmm, that's odd.  In that case, I need to revisit the test and see what kind of stupid I've gotten myself into in there.
