### ISSUE TITLE
Remove support for NetBSD

### ISSUE THREAD

**Issue by genio** [genio/p5-UV#9]
LibUV does not support NetBSD: https://github.com/libuv/libuv/blob/v1.x/SUPPORTED_PLATFORMS.md

Given that and the amount of build failures we're getting with NetBSD < v7, maybe removing support for NetBSD all together is the proper path.

**Comment by Leont** [comment]
I'm not sure what you mean with removing support.

**Comment by genio** [comment]
```die "Unsupported platform" if $^O eq 'NetBSD';``` or some such in Makefile.PL. I actually meant to put this issue in on Alien::libuv. But then I thought, can't hurt to have it here too.

**Comment by genio** [comment]
http://www.cpantesters.org/cpan/report/f0ec0318-89b7-11e7-abde-b912e8d69c8f

```log
06:19 < sgimeno> genio, NetBSD is not a supported platform.
    See: https://github.com/libuv/libuv/blob/v1.x/SUPPORTED_PLATFORMS.md
06:19 < sgimeno> But you can open an issue or even send a
    PR in the repo
06:27 < sgimeno> genio, the code to look should be around
    here: https://github.com/libuv/libuv/blob/v1.x/src/unix/fs.c#L869-L943.
    It shouldn't b too difficult to modify so it fixes de NetBSD issue
```

**Comment by Leont** [comment]
> die "Unsupported platform" if $^O eq 'NetBSD'; or some such in Makefile.PL. I actually meant to put this issue in on Alien::libuv. But then I thought, can't hurt to have it here too.

If you do that, and lib-UV suddenly starts supporting NetBSD, perl-UV would prevent everything from working as intended.

I would disable the CPAN Testers mail if it's bothering you, but otherwise leave it be. CPAN Testers is giving correct results, why hide them?

**Comment by genio** [comment]
Fair enough.

**Comment by krytarowski** [comment]
I will try to fix it.

**Comment by krytarowski** [comment]
https://github.com/libuv/libuv/issues/1564

**Comment by krytarowski** [comment]
NetBSD has now full support in libuv. If there are still problems, alarm me.

**Comment by genio** [comment]
Awesome!  Thanks for all of your work!
